const data = {
  products: [
    {
      _id: "1",
      name: "CEIQ Surgical Skin 1.0",
      category: "skins",
      image: "/images/skin1.jpg",
      price: 15,
      countInStock: 20,
      brand: "CEIQ",
      rating: 3.0,
      numReviews: 10,
      description: "Piel sintética docente",
    },
    {
      _id: "2",
      name: "Juego Lap Aro",
      category: "endo training",
      image: "/images/juegoLap.jpg",
      price: 5,
      countInStock: 10,
      brand: "CEIQ",
      rating: 4.0,
      numReviews: 14,
      description: "Entrenador Laparoscópico CEIQ",
    },
    {
      _id: "3",
      name: "Kit de Sutura CEIQ",
      category: "kits",
      image: "/images/kitSutura.jpg",
      price: 70,
      countInStock: 25,
      brand: "CEIQ",
      rating: 4.8,
      numReviews: 17,
      description:
        "equipo ideal para tus primeros pasos en la realización de sutura y nudos quirúrgicos.",
    },
    {
      _id: "4",
      name: "Simulador Diafragmático",
      category: "endo training",
      image: "/images/diafrag.jpg",
      price: 15,
      countInStock: 45,
      brand: "CEIQ",
      rating: 4.6,
      numReviews: 20,
      description:
        "Simula la reparación de una Hernia Hiatal Laparoscópica y abierta.",
    },
    {
      _id: "5",
      name: "CEIQ  Simulador para inyección intramuscular",
      category: "skins",
      image: "/images/inyIntra.jpg",
      price: 20,
      brand: "CEIQ",
      countInStock: 200,
      rating: 4.5,
      numReviews: 13,
      description:
        "simulador para la aplicación de inyecciones intramusculares simuladas.",
    },
    {
      _id: "6",
      name: "CEIQ Surgical Skin 1.0 MINI",
      category: "skins",
      image: "/images/skin1Mini.jpg",
      price: 5,
      countInStock: 130,
      brand: "CEIQ",
      rating: 4.8,
      numReviews: 25,
      description: "Piel sintética docente en su versión pequeña",
    },
  ],
};

export default data;
